# -*- coding: utf-8 -*-
"""test.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bCu_R8pW0vB3vq7XJfw90L54BVnN73i5

## Imports and Installs
"""

from google.colab import drive

import numpy as np
import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns

import tensorflow as tf

import sklearn
from sklearn.metrics import classification_report, roc_curve, auc, precision_recall_curve, confusion_matrix

print(tf.__version__)
print(pd.__version__)
print(np.__version__)
print(sns.__version__)
print(sklearn.__version__)

drive.mount('/content/gdrive')
root_path = 'gdrive/My Drive/Colab Notebooks/Dchiper/'
test_file = root_path + 'data/wos2class.test.json'

"""## Functions

Preparing the data set:
"""


def dataset_prep(data_file):

    dataset = pd.read_json(data_file)

    dataset['Label'] = dataset['Label'].astype('category')
    dataset['Target'] = dataset['Label'].cat.codes

    titles = dataset['Title'].to_numpy()
    abstracts = dataset['Abstract'].to_numpy()
    labels = dataset['Target'].to_numpy()

    features = [titles, abstracts]

    return features, labels


"""## Testing

Load the model:
"""

model = tf.keras.models.load_model(root_path + 'models')

"""Evaluate the performance:"""

X, y = dataset_prep(test_file)

model.evaluate(X, y)

"""The confusion matrix:"""

predicted = model.predict(X)
predicted_t = (predicted > 0.5)
print(confusion_matrix(y, predicted_t))

"""Heat Map:"""

hmap = sns.heatmap(confusion_matrix(y, predicted_t), cmap='Blues')

"""Calculate presicion, recall, and f1 score:"""

target_names = ['Material Science', 'Chemistry']
print(classification_report(y, predicted_t, target_names=target_names))

"""### ROC and AUC"""

fpr, tpr, threshold = roc_curve(y, predicted)
auc_model = auc(fpr, tpr)

plt.plot(fpr, tpr, color='crimson',
         label='Area Under the Curve = %0.3f' % auc_model)

plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')

plt.legend()
plt.show()

"""### Precision and Recall Curve"""

pre, rec, _ = precision_recall_curve(y, predicted)
auc_prc = auc(rec, pre)

plt.plot(rec, pre, color='seagreen',
         label='Area Under the Curve = %0.3f' % auc_prc)

plt.ylabel('Precision')
plt.xlabel('Recall')

plt.legend()
plt.show()
